account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('find_id/', find_id, name='find_id'),
    path('find_pw/', find_pw, name='find_pw'),
]

board/urls.py
from django.urls import path
from .views import *

app_name = 'board'

urlpatterns = [
    path('', board, name='board'),
    path('write', board_write, name='board_write'),
    path('postwrite', board_write_post, name='board_write_post'),
    path('delete/<p_id>', board_delete, name='board_delete'),
    path('edit/<p_id>', board_edit, name='board_edit'),
    path('<p_type>', board, name='board'),
    path('detail/<id>', board_detail, name='board_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('rental/', include('rental.urls')),
    path('type_test/', include('type_test.urls')),
    path('mypage/', include('mypage.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls'))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('how_to', how_to, name='how_to'),
    path('how_to_clean', how_to_clean, name='how_to_clean'),
    path('how_to_pick', how_to_pick, name='how_to_pick'),
]

rental/urls.py
from django.urls import path
from rental.views import *

app_name = 'rental'

urlpatterns = [
    path('device/list/', device_list, name='device_list_all'),
    path('device/list/<d_values>', device_list, name='device_list'),
    path('device/like/<int:d_id>/', device_like, name="device_like"),
    path('device/<int:d_id>/<d_name>/detail', device_detail, name='device_detail'),
    path('device/<int:d_id>/rent', device_rental, name='device_rental'),
    path('device/<int:d_id>/reserve', device_reserve, name='device_reserve'),
    path('game/list/', game_list, name='game_list_all'),
    path('game/list/device/<g_device>', game_list, name='game_list'),
    path('game/list/genre/<g_genre>', game_list, name='game_list_genre'),
    path('game/like/<int:g_id>/', game_like, name="game_like"),
    path('game/<g_id>/', game_detail, name='game_detail'),
    path('game/<g_id>/rent', game_rental, name='game_rental'),
    path('game/<int:g_id>/reserve', game_reserve, name='game_reserve'),
    path('rental_done', rental_done, name='rental_done'),
    path('reserve_done', reserve_done, name='reserve_done'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.db.models import Count
from django.shortcuts import render


# Create your views here.
from board.models import Post
from rental.models import *


def home(request):
    authuser = request.session.get('authUser')
    dr_day = None
    gr_day = None
    device_rental = None
    game_rental = None
    notice_no = 0
    if authuser:
        user = User.objects.get(member_id=authuser['member_id'])
        today = datetime.now().date()
        device_rental = DeviceRental.objects.filter(member_id=user, overdue=None)
        game_rental = GameRental.objects.filter(member_id=user, overdue=None)
        if device_rental.count() > 0:
            for dr in device_rental:
                if today >= (dr.dreturn_date - timedelta(days=2)) and today < dr.dreturn_date:
                    dr_day = 0
                    notice_no = notice_no + 1
                elif today >= dr.dreturn_date:
                    dr_day = today - dr.dreturn_date
                    dr_day = dr_day.days + 1
                    notice_no = notice_no + 1
                    # d_reserve = DeviceReserve.objects.filter(device_id=dr.device_id)
                    # if d_reserve.count() > 0:
                    #     for drr in d_reserve:
                    #         drr.device_due_date = drr.device_due_date + timedelta(days=r_day)
        if game_rental.count() > 0:
            for gr in game_rental:
                if today >= (gr.greturn_date - timedelta(days=2)) and today < gr.greturn_date:
                    gr_day = 0
                    notice_no = notice_no + 1
                elif today >= gr.greturn_date:
                    gr_day = today - gr.greturn_date
                    gr_day = gr_day.days + 1
                    notice_no = notice_no + 1

    devices = RentalDevice.objects.annotate(d_likes=Count('device_like')).order_by('-d_likes')
    devices = devices[:4]

    games = RentalGame.objects.annotate(g_likes=Count('game_like')).order_by('-g_likes')
    games = games[:4]

    posts = Post.objects.all()
    posts = posts[:7]

    game_v = RentalGame.objects.filter(game_video__isnull=False).values_list('game_video', flat=True)

    return render(request, 'home/home.html', {'dr_day': dr_day, 'device_rental': device_rental, 'gr_day': gr_day, 'game_rental': game_rental, 'notice_no': notice_no, 'devices':devices, 'games': games, 'posts': posts, 'game_v': game_v})


def how_to(request):
    return render(request, 'home/how_to.html')


def how_to_clean(request):
    return render(request, 'home/how_to_clean.html')


def how_to_pick(request):
    return render(request, 'home/how_to_pick.html')

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
{% endblock %}
{% block style %}
<style>
    .container{
        position: relative;
        height: 1200px;
        padding: 0;
    }
    .shop{
        position: relative;
        color: #F6F1EBFF;
        font-family: 'Dunggeunmo', sans-serif;
    }
    .shop a{
        color: #F6F1EBFF;
    }
    .shop_top{
        position: relative;
        width: 100%;
        height: 202.5px;
        background-image: url({% static 'image/shop_top.png' %});
        background-size: 295px auto;
    }
    .shop_wall{
        position: absolute;
        top: 183px;
        width: 100%;
        height: 720px;
        border-bottom: 10px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 9;
        border-image-repeat: round;
        background-image: url({% static 'image/header_back_3.png' %});
        background-size: 95px auto;
    }
    .shop_floor{
        position: absolute;
        bottom: 200px;
        width: 100%;
        height: 100px;
        background-image: url({% static 'image/header_back_4.png' %});
        background-size: 100px auto;
    }
    .shop_tv{
        position: absolute;
        top: 190px;
        left: 100px;
        width: 500px;
        height: 300px;
        background-image: url({% static 'image/tv.png' %});
        background-size: 500px auto;
    }
    iframe{
        margin-top: 56px;
        margin-left: 48px;
        width: 380px;
        height: 212px;

        background-color: black;
    }
    .shop_item{
        padding: 20px;
        position: absolute;
        right: 100px;
        height: 260px;
        background-color: gray;
        border: 13px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 12;
        border-image-repeat: round;
    }
    .sboard{
        border: 15px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 13;
        border-image-repeat: round;
        background-color: #E4BD74FF;
        background-image: url({% static 'image/header_back_1.png' %});
        background-size: 100px auto;
        left: 100px;
        top: 520px;
        width: 500px;
        height: 430px;
        padding: 15px;
    }
    .sboard .more{
        bottom: 30px;
        right: 30px;
    }
    .board_contents{
        padding: 50px;
        color: #33312CFF;
        width: 100%;
        height: 100%;
        background-image: url({% static 'image/게시판.png' %});
        background-size: 100% 100%;
    }
    .board_contents a{
        color: #33312CFF;
    }
    .sg{
        width: 450px;
        top: 230px;
        text-align: center;
        background-image: url({% static 'image/header_back_1.png' %});
        background-size: 67px auto;
    }
    .game_list{
        margin-top: 20px;
        display: flex;
        justify-content: space-between;
    }
    .game{
        width: 90px;
    }
    .game img{
        width: 80px;
    }
    .game_img_div{
       display: flex;
       align-items: center;
       height: 90px;
       background-color: white;
       border: 5px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 13;
        border-image-repeat: round;
    }

    .device_list{
        margin-top: 20px;
        display: flex;
        justify-content: space-between;
    }
    .device{
        width: 90px;
    }
    .pub{
        font-size: 15px;
        color: gray;
    }
    .device_img_div{
       display: flex;
       align-items: center;
       height: 90px;
       background-color: white;
       border: 5px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 13;
        border-image-repeat: round;
    }
    .device img{
        width: 80px;
    }
    ul{
        padding: 0;
    }
    li{
        list-style: none;
    }
    .price{
        position: absolute;
        bottom: 0;
        left: 5px;
        line-height: 35px;
    }
    .sd{
        width: 450px;
        top: 520px;
        text-align: center;
        background-image: url({% static 'image/header_back_1.png' %});
        background-size: 67px auto;
    }
    .ss{
        width: 430px;
        padding: 0;
        height: 130px;
        bottom: 250px;
        display: flex;
        justify-content: space-between;
        background: none;
        border: none;
    }
    .more{
        position: absolute;
        bottom: 5px;
        right: 5px;
    }
    .ss a div{
        position: relative;
        width: 130px;
        height: 130px;
    }
    .ss a div p{
        position: absolute;
        width: 100%;
        color: #F6F1EBFF;
        bottom: -45px;
        text-align: center;
        font-size: 20px;
        text-shadow: -2px 0 #5F381EFF, 0 2px #5F381EFF, 2px 0 #5F381EFF, 0 -2px #5F381EFF;
    }
    .shop_potion1{
        background-image: url({% static 'image/potion1.png' %});
        background-size: 130px;
    }
    .shop_book1{
        background-image: url({% static 'image/book1.png' %});
        background-size: 130px;
    }
    .shop_book2{
        background-image: url({% static 'image/book2.png' %});
        background-size: 130px;
    }
    .shop_sign{
        text-align: center;
        font-size: 20px;
        font-weight: bold;
    }
    .shop_side{
        border-left: 10px solid transparent;
        border-right: 10px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 9;
        border-image-repeat: round;
        background-image: url({% static 'image/header_back.png' %});
        background-size: 100px auto;
        width: 75px;
        height: 800px;
    }
    .left{
        position: relative;
        left: 0;
    }
    .right{
        position: absolute;
        right: 0;
        top: 203px;
    }
    .shop_bottom{
        width: 100%;
        position: relative;
        height: 200px;
        border-left: 10px solid transparent;
        border-top: 10px solid transparent;
        border-right: 10px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 9;
        border-image-repeat: round;
        background-image: url({% static 'image/header_back_2.png' %});
        background-size: 100px auto;
    }
</style>
{% endblock %}
{% block content %}
<div class="shop">
    <div class="shop_wall"></div>
    <div class="shop_tv">
        <iframe src="{{game_v|random}}?autoplay=1&mute=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </iframe>
    </div>
    <div class="shop_top">

    </div>
    <div class="shop_floor"></div>
    <div class="shop_item sg">
        <div class="shop_sign">인기게임</div>

        <div class="game_list">
            {% for g in games %}
            <a href="{{g.get_gabsolute_url}}"><div class="game">
                <div class="game_img_div"><img src="{{g.game_image.url}}"></div>
                <p>{{g.game_name}}</p>
            </div>
            </a>
            {% endfor %}
        </div>

        <div class="more"><a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'rental:game_list_all' %}{% endif %}">더보기</a></div>
    </div>
    <div class="shop_item sboard">
        <div class="board_contents">
            <div class="shop_sign">게시판</div>
            {% for p in posts %}
            <a href="{{p.get_post_url}}"><p>{{p.postname}}</p></a>
            {% endfor %}
        </div>
        <div class="more"><a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'board:board' %}{% endif %}">더보기</a></div>
    </div>
    <div class="shop_item sd">
        <div class="shop_sign">인기기기</div>

        <div class="device_list">
            {% for d in devices %}
            <a href="{{d.get_dabsolute_url}}"><div class="device">
                <div class="device_img_div"><img class="device_img" src="{{d.device_image.url}}"></div>
                <p>{{d.device_name}}</p>
            </div>
            </a>
            {% endfor %}
        </div>
        <div class="more"><a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'rental:device_list_all' %}{% endif %}">더보기</a></div>
    </div>
    <div class="shop_item ss">
        <a href="{% url 'home:how_to' %}"><div class="shop_book1">
            <p>대여 방법</p>
        </div></a>
        <a href="{% url 'home:how_to_pick' %}"><div class="shop_book2">
            <p>반납 방법</p>
        </div></a>
        <a href="{% url 'home:how_to_clean' %}"><div class="shop_potion1">
            <p>세척 과정</p>
        </div></a>
    </div>
    <div class="shop_side left"></div>
    <div class="shop_side right"></div>
    <div class="shop_bottom"></div>
</div>
{% endblock %}

home/templates/home/how_to.html
{% extends 'base.html' %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
{% endblock %}
{% block style %}
<link rel="preconnect" href="https://fonts.googleapis.com" xmlns="http://www.w3.org/1999/html">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400&display=swap" rel="stylesheet">
<script>
    // html dom 이 다 로딩된 후 실행된다.
    $(document).ready(function(){
        // menu를 클릭했을때
        $(".menu").click(function(){
            var submenu = $(this).next("p");
            // submenu 가 화면상에 보일때는 위로 부드럽게 접고 아니면 아래로 부드럽게 펼치기
            if( submenu.is(":visible") ){
                submenu.slideUp();
            }else{
                submenu.slideDown();
            }
        });
    });
</script>

<style>
    div.container{
        background: #6A386E;
        padding: 50px;
        font-family: "Noto Sans KR",sans-serif;
    }
    div.content{
        background: #EDE7C5;
    }
    h2, h3, h1, p {
        margin: 0;
    }
    .container h1{
        text-align: center;
        line-height: 150%;
    }
    h2{
        margin: 0;
        font-size: 32px;
        line-height: 40px;
    }
    h3{
        margin: 0;
        font-size: 20px;
    }
    section p{
        margin-top: 16px;
        line-height: 150%;
        font-size: 16px;
    }
    section.section1, section.section3, section.section4{
        padding: 80px 40px;
    }
    section.section2{
        padding: 80px 125px;
    }
    section.section5{
        padding: 16px 130px 80px;
        margin-bottom: 25px;
    }

    header.how_to{
        padding: 45px 0;
        background: url("../../../static/image/how_to.jpg") no-repeat;
        background-size: cover;
        background-position: center;
        text-align: center;
        color: white;
    }
    header.how_to h1{
        font-weight: bold;
    }

    section.section1{
        overflow: hidden;
    }
    div.rental_device_img{
        float: left;
        width: 50%;
    }
    div.rental_device_article{
        float: left;
        width: 50%;
    }

    section.section2{
        overflow: hidden;
    }
    div.rental_one{
        float: left;
        width: 50%;
    }
    div.rental_two{
        float: left;
        width: 50%;
    }
    .number{
        width: 32px;
        height: 32px;
        background: #D0B0F4;
        color: #623265;
        border-radius: 9999px;
        display: inline-block;
        margin: 0 20px 0 0;
        font-size: 20px;
        text-align: center;
    }

    section.section3{
        overflow: hidden;
    }
    div.rental_calendar{
        float: left;
        text-align: center;
        width: 50%;
    }
    div.rental_calendar_article{
        float: left;
        width: 50%;
    }
    div.rental_calendar_article table{
        line-height: 220%;
        width: 70%;
    }
    .container table{
        padding: 16px 0;
    }
    .gray {
        color: #636C73;
        font-size: 14px;
        font-weight: 500;

    }
    .black{
        color: #21242A;
        font-size: 18px;
        font-weight: 400;
    }

    section.section4{
        overflow: hidden;
    }
    div.rental_shipping{
        float: left;
        text-align: center;
        width: 50%;
    }
    div.rental_shipping_article{
        float: left;
        width: 50%;
    }

    .menu {cursor:pointer;}
    .hide {display:none;}
    section.section5 h1{
        padding: 16px 0;
        font-size: 18px;
    }
    p.menu{
        font-size: 18px;
        margin: 0;
        padding: 16px 0px 16px 24px;
    }
    p.hide{
        font-size: 14px;
        line-height: 150%;
        margin: 0;
        padding: 0 0 16px 40px;
    }

</style>
{% endblock %}
{% block content %}
<div class="content">
<header class="how_to">
    <h1>빠르고 간편한 대여 방법</h1>
    <p>깨끗이 살균해서 보내드려요</p>
</header>

<section class="section1">
    <div class="rental_device_img">
        <img src="../../../static/image/how_to_game.png" alt="써보고 싶은 제품" width="460px">
    </div>
    <div class="rental_device_article">
        <h2>
            써보고 싶은 제품을
            <br>모~두 빌려보세요!
        </h2>
        <p>
            대여할 수 있는 제품에 갯수 제한은 없습니다.
            <br>한 번에 원하시는 제품을
            <br>다~! 빌려보실 수 있습니다.
        </p>
    </div>
</section>
<section class="section2">
    <div class="rental_one">
        <div class="flex-2">
            <h3><div class="number">1</div>원하는 제품을 대여하세요.</h3>
            <p>유튜브, 리뷰 찾아볼 시간에 직접 써보세요.<br>직접 써보는 게 더 확실합니다.</p>
        </div>
    </div>
    <div class="rental_two">
        <div class="flex-2">
            <h3><div class="number">2</div>원하시는 기간을 선택하세요.</h3>
            <p>14일이면 필요한 제품인지 아닌지 알 수 있습니다.<br>대여 기간이 부족하다면 더 대여해보세요.</p>
        </div>
    </div>
</section>
<section class="section3">
    <div class="rental_calendar">
        <img src="../../../static/image/how_to_calendar.png" alt="달력" width="460px">
    </div>
    <div class="rental_calendar_article">
        <div class="flex-3">
            <h2>대여 기간을 확인해주세요</h2>
            <p>오늘 대여하면 내일부터 대여 시작일!<br>대여기간은 14일 고정입니다.</p>
            <table>
                <tr>
                    <td><span class="gray">10일</span><br><b><span class="black">대여시작일</span></b></td>
                    <td><span class="gray">07시 이전</span><br><b><span class="black">배송도착!</span></b></td>
                </tr>
                <tr>
                    <td><span class="gray">24일</span><br><b><span class="black">반납일 전날</span></b></td>
                    <td><span class="gray">20시</span><br><b><span class="black">반납접수!</span></b></td>
                </tr>
                <tr>
                    <td><span class="gray">25일</span><br><b><span class="black">반납일</span></b></td>
                    <td><span class="gray">20시 이전</span><br><b><span class="black">배송받은 장소에 내놓기!</span></b></td>
                </tr>


            </table>
        </div>
    </div>
</section>
<section class="section4">
    <div class="rental_shipping">
        <img src="../../../static/image/how_to_shipping.png" alt="새벽 배송" width="380px">
    </div>
    <div class="rental_shipping_article">
        <div class="flex-4">
            <h2>빠르고 조용하게<br>새벽배송 해드려요!</h2>
            <p>대여를 했는데 늦게 도착하면 시간이 아깝잖아요.<br>공동현관 출입방법은 자세하게 부탁드려요!</p>
        </div>
    </div>
</section>
<section class="section5">
<h1>자주 묻는 질문</h1>
    <p class="menu">Q.제품은 언제 도착하나요?</p>
        <p class="hide">
            A.대여 시작일 하루 전 22시부터 배송이 시작됩니다.
            <br>
            배송이 늦은 시간에 이루어지기 때문에 배송 시 특이사항(ex.공동현관 비밀번호)을 잊지말고 기입해주세요.
        </p>

    <p class="menu">Q.제품에 하자가 있어요.</p>
        <p class="hide">
            A.제품들은 검수 및 소독이 완료된 리퍼 제품으로 생활기스가 있을 수 있습니다.
            <br>안심하고 쓰셔도 됩니다😊
            <br>제품이 작동하지 않을 시 고객센터로 연락주시면 빠르게 도와드리겠습니다.
        </p>

    <p class="menu">Q.여러 제품을 동시에 대여할 수 있나요?</p>
        <p class="hide">
            A.기기의 경우 하나만 대여가 가능합니다. 게임은 여러 개의 제품 대여가 가능합니다.
            <br><font color ="#b7660">* 걱정마세요!
            <br>배송비는 묶음 결제와 금액은 똑같습니다.
            </font>
        </p>

    <p class="menu">Q.제가 결제하고 가족/친구가 써도 되나요?</p>
        <p class="hide">
            A.제품 이용은 가능하지만, 제품의 분실 및 훼손에 대한 책임은 친구/가족에게 양도할 수 없습니다.
        </p>

    <p class="menu">Q.여러 제품을 동시에 대여할 수 있나요?</p>
        <p class="hide">
            A.기기의 경우 하나만 대여가 가능합니다. 게임은 여러 개의 제품 대여가 가능합니다.
            <br><font color ="#b7660">* 걱정마세요!
            <br>배송비는 묶음 결제와 금액은 똑같습니다.
            </font>
        </p>

    <p class="menu">Q.제가 결제하고 가족/친구가 써도 되나요?</p>
        <p class="hide">
            A.제품 이용은 가능하지만, 제품의 분실 및 훼손에 대한 책임은 친구/가족에게 양도할 수 없습니다.
        </p>

    <p class="menu">Q.반납 요청은 어떻게 하나요?</p>
        <p class="hide">
            A.반납일 하루 전 반납 요청을 위해 알림이 발송됩니다.
            <br>"마이페이지 > 기기･게임대여목록"에서 반납 요청하실 수 있습니다.
        </p>

    <p class="menu">Q.반납 날짜를 못 지켰어요.</p>
        <p class="hide">
            A.연락이 닿지 않거나 연체된 기간 이후에도 반납하지 않으실 경우 제품정가의 150%에 해당하는
            <br>금액이 청구될 수 있습니다.
            <br>자세한 안내사항은 고객센터로 연락주세요.
        </p>

    <p class="menu">Q.대여 이용 중 제품이 파손됐어요.</p>
        <p class="hide">
            A.파손/분실된 제품 및 구성품은 동의하신 이용약관에 따라 보상금액이 청구될 수 있습니다.
        </p>

    <p class="menu">Q.제품 사용방법이 궁금해요!</p>
        <p class="hide">
            A.대여하신 제품의 상세페이지에서 제품 정보를 확인하실 수 있습니다.
            <br>*대여 시 사용방법 메뉴얼을 동봉해드리지 않는 이유는 분실 및 훼손에 대한 우려가 있어
            <br>동봉해드리지 않고 있습니다. 이 점 양해바랍니다.
        </p>
</section>
</div>
{% endblock %}