config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('rental/', include('rental.urls')),
    path('type_test/', include('type_test.urls')),
    path('mypage/', include('mypage.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls'))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('how_to', how_to, name='how_to'),
    path('how_to_clean', how_to_clean, name='how_to_clean'),
    path('how_to_pick', how_to_pick, name='how_to_pick'),
]

mypage/urls.py
from django.urls import path
from .views import *

app_name = 'mypage'

urlpatterns = [
    path('mypage_user', mypage_user, name='mypage'),
    path('mypage_useredit', mypage_useredit, name='mypage_useredit'),
    path('mypage_game', mypage_game, name='mypage_game'),
    path('mypage_device', mypage_device, name='mypage_device'),
    path('mypage_like', mypage_like, name='mypage_like'),
    path('mypage_like/game/<int:g_id>', mypage_Gdislike, name='mypage_Gdislike'),
    path('mypage_like/device/<int:d_id>', mypage_Ddislike, name='mypage_Ddislike'),
    path('dreserve_delete/<int:drs_id>', dreserve_delete, name='dreserve_delete'),
    path('device_return/<int:dr_id>', device_return, name='device_return'),
    path('greserve_delete/<int:grs_id>', greserve_delete, name='greserve_delete'),
    path('game_return/<int:gr_id>', game_return, name='game_return'),
    path('mypage_board', mypage_board, name='mypage_board'),
]

rental/urls.py
from django.urls import path
from rental.views import *

app_name = 'rental'

urlpatterns = [
    path('device/list/', device_list, name='device_list_all'),
    path('device/list/<d_values>', device_list, name='device_list'),
    path('device/like/<int:d_id>/', device_like, name="device_like"),
    path('device/<int:d_id>/<d_name>/detail', device_detail, name='device_detail'),
    path('device/<int:d_id>/rent', device_rental, name='device_rental'),
    path('device/<int:d_id>/reserve', device_reserve, name='device_reserve'),
    path('game/list/', game_list, name='game_list_all'),
    path('game/list/device/<g_device>', game_list, name='game_list'),
    path('game/list/genre/<g_genre>', game_list, name='game_list_genre'),
    path('game/like/<int:g_id>/', game_like, name="game_like"),
    path('game/<g_id>/', game_detail, name='game_detail'),
    path('game/<g_id>/rent', game_rental, name='game_rental'),
    path('game/<int:g_id>/reserve', game_reserve, name='game_reserve'),
    path('rental_done', rental_done, name='rental_done'),
    path('reserve_done', reserve_done, name='reserve_done'),
]

rental/views.py
import random
from datetime import timedelta
import datetime

from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.dateformat import DateFormat
from django.utils.dateparse import parse_date
from django.utils.datetime_safe import datetime
from django.core.paginator import Paginator

from .models import *
# Create your views here.


def device_list(request, d_values=None):
    current_value = None
    device_values = DeviceValues.objects.all()
    devices = RentalDevice.objects.all()
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])

    page = request.GET.get('page', '1')  # 페이지
    if d_values:
        current_value = get_object_or_404(DeviceValues, values=d_values)
        devices = devices.filter(device_value=current_value)

    device_sort = request.GET.get('device_sort')
    if device_sort == '01':
        devices = devices.annotate(d_likes=Count('device_like')).order_by('-d_likes')
    elif device_sort == '02':
        devices = devices.order_by('device_rfee')
    elif device_sort == '03':
        devices = devices.order_by('-device_rfee')
    elif device_sort == '04':
        devices = devices.order_by('-device_pub')

    device_check = request.GET.get('device_check')
    dc = None
    if device_check:
        devices = devices.filter(device_check=0)
        dc = 1
    else:
        dc = None

    paginator = Paginator(devices, 20)  # 페이지당 20개씩 보여주기
    page_obj = paginator.get_page(page)

    return render(request, 'rental/device_list.html',
                  {'current_value': current_value, 'device_values': device_values, 'devices': page_obj, 'i': i, 'dc': dc})


def device_detail(request, d_id, d_name=None):
    device = get_object_or_404(RentalDevice, device_id=d_id, device_name=d_name)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])

    command_games = list(RentalGame.objects.filter(device_value=device.device_value))
    if len(command_games) < 5:
        command_games = random.sample(command_games, len(command_games))
    else:
        command_games = random.sample(command_games, 5)

    if DeviceRental.objects.filter(member_id=i, overdue=None).count() > 0:
        already = True
    else:
        already = False
    return render(request, 'rental/device_detail.html', {'device': device, 'authuser': authuser, 'already': already, 'command_games':command_games})


def device_like(request, d_id):
    d = get_object_or_404(RentalDevice, device_id=d_id)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    if i in d.device_like.all():
        d.device_like.remove(i)
    else:
        d.device_like.add(i)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def device_rental(request, d_id):
    device = get_object_or_404(RentalDevice, device_id=d_id)
    authuser = request.session.get('authUser')
    tomorrow = get_drental_date().strftime('%Y.%m.%d')
    return_date = get_drental_date() + timedelta(days=15)
    return_date_p = return_date.strftime('%Y.%m.%d')
    if request.method == 'POST':
        d_rent = DeviceRental()
        d = RentalDevice.objects.get(device_id=d_id)
        d_rent.device_id = d
        l_check = DeviceRental.objects.last()
        if l_check == None:
            d_rent.device_rental_id = 1
        else:
            l = DeviceRental.objects.latest('device_rental_id')
            d_rent.device_rental_id = l.device_rental_id + 1
        if not request.POST['another_address']:
            d_rent.daddress = authuser['address']
        else:
            d_rent.daddress = request.POST['another_address']
            d_rent.daddress += " " + request.POST['another_address_detail']
        i = User.objects.get(member_id=authuser['member_id'])
        d_rent.member_id = i
        d_rent.dreturn_date = return_date
        d_rent.save()

        device.device_check = 1
        device.save()

        return redirect('/rental/rental_done')
    else:
        return render(request, 'rental/device_rental.html',
                      {'authuser': authuser, 'tomorrow': tomorrow, 'return_date': return_date_p, 'device': device,})


def device_reserve(request, d_id):
    device = get_object_or_404(RentalDevice, device_id=d_id)
    dr = DeviceRental.objects.filter(device_id=d_id)
    dr = dr.last()
    device_reserve_count = DeviceReserve.objects.filter(device_id=d_id).count()
    today = datetime.now().date()
    overdue = False
    if device_reserve_count == 0:
        if today > dr.dreturn_date:
            due_date = today + timedelta(days=4)
            overdue = True
        else:
            due_date = dr.dreturn_date + timedelta(days=2)
    else:
        drs = DeviceReserve.objects.filter(device_id=d_id)
        c = 1 + drs.count()*16
        due_date = dr.dreturn_date + timedelta(days=c)
    due_date_p = due_date.strftime('%Y.%m.%d')
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    command_games = list(RentalGame.objects.filter(device_value=device.device_value))
    if len(command_games) < 5:
        command_games = random.sample(command_games, len(command_games))
    else:
        command_games = random.sample(command_games, 5)
    if request.method == 'POST':
        d_reserve = DeviceReserve()
        dd = RentalDevice.objects.get(device_id=d_id)
        d_reserve.device_id = dd
        l_check = DeviceReserve.objects.last()
        if l_check == None:
            d_reserve.device_reserve_id = 1
        else:
            l = DeviceReserve.objects.latest('device_reserve_id')
            d_reserve.device_reserve_id = l.device_reserve_id + 1

        i = User.objects.get(member_id=authuser['member_id'])
        d_reserve.member_id = i

        d_reserve.device_due_date = due_date

        d_reserve.save()

        device.device_check = 1
        device.save()

        return redirect('/rental/reserve_done')
    else:
        u_already = DeviceReserve.objects.filter(member_id=i).count()
        due_start = due_date - timedelta(days=2)
        due_end = due_date - timedelta(days=1)
        return render(request, 'reserve/device_reserve.html',
                      {'device': device, 'due_start': due_start, 'due_end': due_end, 'due_date': due_date_p, 'authuser': authuser,
                       'u_already': u_already, 'device_reserve_count': device_reserve_count, 'overdue': overdue, 'command_games':command_games})


def game_list(request, g_device=None, g_genre=None):
    current_device = None
    game_devices = DeviceValues.objects.all()

    current_genre = None
    game_genres = Genre.objects.all()

    games = RentalGame.objects.all()
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    page = request.GET.get('page', '1')  # 페이지

    if g_device:
        current_device = get_object_or_404(DeviceValues, values=g_device)
        games = games.filter(device_value=current_device)

    if g_genre:
        current_genre = get_object_or_404(Genre, genre=g_genre)
        games = games.filter(genre=current_genre)

    game_sort = request.GET.get('game_sort')
    if game_sort == '01':
        games = games.annotate(g_likes=Count('game_like')).order_by('-g_likes')
    elif game_sort == '02':
        games = games.order_by('game_rfee')
    elif game_sort == '03':
        games = games.order_by('-game_rfee')

    game_check = request.GET.get('game_check')
    gc = None
    if game_check:
        games = games.exclude(game_stock=0)
        gc = 1

    paginator = Paginator(games, 20)  # 페이지당 20개씩 보여주기
    page_obj = paginator.get_page(page)

    return render(request, 'rental/game_list.html',
                  {'current_device': current_device, 'game_devices': game_devices, 'games': page_obj, 'i': i, 'current_genre': current_genre, 'game_genres': game_genres, 'gc': gc})


def game_like(request, g_id):
    g = get_object_or_404(RentalGame, game_id=g_id)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    if i in g.game_like.all():
        g.game_like.remove(i)
    else:
        g.game_like.add(i)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def game_detail(request, g_id):
    game = get_object_or_404(RentalGame, game_id=g_id)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    command_games = list(RentalGame.objects.filter(genre=game.genre).exclude(game_id=g_id))
    if len(command_games) < 5:
        command_games = random.sample(command_games, len(command_games))
    else:
        command_games = random.sample(command_games, 5)
    if GameRental.objects.filter(game_id=g_id, member_id=i, overdue=None).count() > 0:
        already = True
    else:
        already = False
    return render(request, 'rental/game_detail.html', {'game': game, 'authuser': authuser, 'already': already, 'command_games': command_games},)


def game_rental(request, g_id):
    game = get_object_or_404(RentalGame, game_id=g_id)
    authuser = request.session.get('authUser')
    tomorrow = get_drental_date().strftime('%Y.%m.%d')
    return_date = get_drental_date() + timedelta(days=15)
    return_date_p = return_date.strftime('%Y.%m.%d')
    if request.method == 'POST':
        g_rent = GameRental()
        g = RentalGame.objects.get(game_id=g_id)
        g_rent.game_id = g
        l_check = GameRental.objects.last()
        if l_check is None:
            g_rent.game_rental_id = 1
        else:
            l = GameRental.objects.latest('game_rental_id')
            g_rent.game_rental_id = l.game_rental_id + 1
        if not request.POST['another_address']:
            g_rent.gaddress = authuser['address']
        else:

rental/templates/rental/device_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Category Page{% endblock %}
{% block style %}
<style>
    h5{
        font-size: 16px;
        display: inline;
    }
    p{
        margin: 0;
    }
    .form{
        margin-left: 10px;
    }
    .active{
        color:red;
    }
    .options{
        position: relative;
    }
    .sorts{
        position: absolute;
        right: 10px;
        top: 10px;
        display: flex;
    }
    .device_list{
        display:flex;
        flex-wrap: wrap;
        padding: 28px;
        border: 2px solid white;
    }
    .device{
        position: relative;
        padding: 10px;
        width: 200px;
        height: 320px;
        margin-bottom: 20px;
        margin-right: 20px;
        border: 1px solid lightgray;
        border-radius: 5px;
    }
    .device:nth-child(5n){
        margin-right: 0;
    }
    .pub{
        font-size: 15px;
        color: gray;
    }
    .device_img_div{
        position: relative;
       display: flex;
       align-items: center;
       width: 180px;
       height: 230px;
    }
    .device_img_div p{
        position: absolute;
        bottom: 0;
        right: 0;
        font-size: 13px;
        margin: 0;
        background-color: white;
    }
    .device_img{
        width: 180px;
    }
    ul{
        padding: 0;
    }
    li{
        list-style: none;
    }
    .price{
        position: absolute;
        bottom: 0;
        left: 5px;
        line-height: 35px;
    }
    .device_able{
        position: absolute;
        line-height: 35px;
        bottom: 0;
        right: 35px;
        margin: 0;
    }
    .like img{
        width: 25px;
    }
    .like{
        position: absolute;
        bottom: 0;
        right: 5px;
    }
    .page{
        width: 100%;
        display: flex;
        justify-content: center;
    }
    .page li{
        margin-left: 10px;
        margin-right: 10px;
    }
    .c_page a{
        color: blue;
    }
</style>
{% endblock %}
{% block script %}
<script>
 $(document).ready(function() {
    $('select[name=device_sort]').change(function () {
        device_sort = $('select[name=device_sort]').val();
        $('.form').submit();
    });
});
function check() {
    game_check = 1
    $('.form2').submit();
};
function check1() {
    game_check = None
    $('.form2').submit();
};
</script>
{% endblock %}
{% block content %}
<a href="{% url 'rental:device_list_all' %}" style="font-weight: 900;">기기 대여</a>
<div class="">
    <div class="options">
        <div class="device_values">
            <a href="{% url 'rental:device_list_all' %}" class="list-group-item {% if not current_value%}active{% endif %}">전체</a><br>
            PlayStation :
            {%for d in device_values %}
                {% if d.platform == 'PS' %}
                    <a href="{{d.get_absolute_url}}" class="list-group-item {% if current_value.values == d.values %}active{% endif %}">{{d.values}}</a>
                {% endif %}
            {% endfor %} |
            Nintendo :
            {%for d in device_values %}
                {% if d.platform == 'ND' %}
                    <a href="{{d.get_absolute_url}}" class="list-group-item {% if current_value.values == d.values %}active{% endif %}">{{d.values}}</a>
                {% endif %}
            {% endfor %}
        </div>
        <div class="sorts">
            <form method="get" action="" class="form2">
                {% if dc == 1 %}
               <label for="device_check1">대여 가능한 게임만 보기</label><input name="device_check1" type="checkbox" id="device_check1" value="1" checked onclick="check1()">
                {% else %}
               <label for="device_check">대여 가능한 게임만 보기</label>
                <input name="device_check" type="checkbox" id="device_check" value="1" onclick="check()">
                {% endif %}
            </form>
            <form method="get" action="" class="form">
                <select name="device_sort" id="device_sort">
                    <option value="0" selected>정렬</option>
                    <option value="01">인기순</option>
                    <option value="02">가격 낮은 순</option>
                    <option value="03">가격 높은 순</option>
                    <option value="04">출시일 순</option>
                </select>
            </form>
        </div>

    </div>
    <div class="col">
        <br>
        <div class="alert alert-info" role="alert">
            {% if current_value %}
                {{current_value.values}}
            {% else %}
                전체 기기
            {% endif %}
        </div>
<div class="device_list">
            {% for rd in devices %}
                <a href="{% if rd.device_check == 0 %}
                           {{rd.get_dabsolute_url}}
                          {% else %}
                            {{rd.get_dreserve_url}}
                            {% endif %}">
                    <div class="device">
                    <div class="device_img_div">
                        <img class="device_img" src="{{rd.device_image.url}}" alt="device image">
                        <p>상태 : {{ rd.device_state }}</p>
                    </div>
                    <div>
                        <h5 class="card-title">{{rd.device_name|upper}}</h5>
                        <span class="pub">{{rd.device_pub|date:"Y"}}</span>
                        <p class="price">{{rd.device_rfee|intcomma}}원</p>
                        {% if rd.device_check == 0 %}
                            <p class="device_able">대여 가능</p>
                        {% else %}
                            <p class="device_able">예약하기</p>
                        {% endif %}
                        <a class="like" href="{% url 'rental:device_like' rd.device_id %}">
                            {% if i in rd.device_like.all %}
                            <img src="{% static 'image/like.png' %}">
                            {% else %}
                            <img src="{% static 'image/dislike.png' %}">
                            {% endif %}
                        </a>
                    </div>
                </div></a>
            {% endfor %}
        </div>
        <!-- 페이징처리 시작 -->
    <ul class="page">
        <!-- 이전페이지 -->
        {% if devices.has_previous %}
        <li>
            <a href="?page={{ devices.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li>
            <a tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->

        {% for page_number in devices.paginator.page_range %}
            {% if page_number == devices.number %}
            <li class="c_page">
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li>
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if devices.has_next %}
        <li>
            <a href="?page={{ devices.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li>
            <a tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


    </div>
</div>

{% endblock %}

rental/templates/rental/game_list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% load static %}
{% load humanize %}
{% block style %}
<style>
    .active{
        color:red;
    }
    h5{
        font-size: 16px;
        display: inline;
    }
    p{
        margin: 0;
    }
    label:hover{
         cursor: pointer;
    }
    input#toggle1 { display: none; }
    input#toggle1 + .menu1 { display: none; }
    input#toggle1:checked + .menu1 { display: block; }


    input#toggle2 { display: none; }
    input#toggle2 + .menu2 { display: none; }
    input#toggle2:checked + .menu2 { display: block; }

    .options{
        position: relative;
    }
    .sorts{
        position: absolute;
        right: 10px;
        top: 10px;
        display: flex;
    }
    .game_list{
        display:flex;
        flex-wrap: wrap;

        padding: 30px;
    }
    .game{
        position: relative;
        padding: 5px;
        width: 200px;
        height: 330px;
        border: 2px solid black;
        margin-bottom: 20px;
        margin-right: 20px;
        border: 1px solid lightgray;
        border-radius: 5px;
    }
    .game:nth-child(5n){
        margin-right: 0;
    }
    .device_value{
        font-size: 15px;
        color: gray;
    }
    .game_img_div{
       display: flex;
       align-items: center;
       width: 180px;
       height: 200px;
    }
    .game_img{
        width: 180px;
    }
    .options{
        position: relative;
    }
    .sorts{
        position: absolute;
        right: 10px;
        top: 10px;
        display: flex;
    }
    .form{
        margin-left: 10px;
    }
    .price{
        position: absolute;
        bottom: 0;
        left: 5px;
        line-height: 35px;
    }
    .game_able{
        position: absolute;
        line-height: 35px;
        bottom: 0;
        right: 35px;
        margin: 0;
    }
    .like img{
        width: 25px;
    }
    .like{
        position: absolute;
        bottom: 0;
        right: 5px;
    }
    .page{
        width: 100%;
        display: flex;
        justify-content: center;
    }
    .page li{
        margin-left: 10px;
        margin-right: 10px;
    }
    .c_page a{
        color: blue;
    }
</style>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('select[name=game_sort]').change(function () {
        game_sort = $('select[name=game_sort]').val();
        $('.form').submit();
    });
});
function check() {
    game_check = 1
    $('.form2').submit();
};
function check1() {
    game_check = None
    $('.form2').submit();
};
</script>
{% endblock %}
{% block content %}
<a href="{% url 'rental:game_list_all' %}" style="font-weight: 900;">게임 대여</a>
    <div class="options">
        <div>
            <label class='text' for='toggle1'>
                기기별로 보기
            </label>
            |
            <label class='text' for='toggle2'>
                장르별로 보기
            </label>
        </div>
        <div>
            <input type='checkbox' id='toggle1'>
            <div class='menu1'>
                <a href="{% url 'rental:game_list_all' %}" class="list-group-item {% if not current_device%}active{% endif %}">All</a>
                {%for g in game_devices %}
                    <a href="{{g.get_gdabsolute_url}}" class="list-group-item {% if current_device.values == g.values %}active{% endif %}">{{g.values}}</a>
                {% endfor %}
            </div>
            <input type='checkbox' id='toggle2'>
            <div class="menu2">
                <a href="{% url 'rental:game_list_all' %}" class="list-group-item {% if not current_genre%}active{% endif %}">All</a>
                {% for gg in game_genres %}
                    <a href="{{gg.get_absolute_url}}" class="{% if current_genre.genre == gg.genre %}active{% endif %}">{{gg.genre}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="sorts">
        <form method="get" action="" class="form2">
            {% if gc %}
           <label for="game_check1">대여 가능한 게임만 보기</label>
            <input name="game_check1" type="checkbox" id="game_check1" value="1" checked onclick="check1()">
            {% else %}
           <label for="game_check">대여 가능한 게임만 보기</label>
            <input name="game_check" type="checkbox" id="game_check" value="1" onclick="check()">
            {% endif %}
        </form>
        <form method="get" action="" class="form">
          <select name="game_sort" id="game_sort">
            <option value="0" selected>정렬</option>
            <option value="01">인기순</option>
            <option value="02">가격 낮은 순</option>
            <option value="03">가격 높은 순</option>
          </select>
        </form>
        </div>
        <div>{% if current_genre %}
            {{current_genre.genre}}
            {% elif current_device %}
            {{current_device}}
        {% else %}
            전체 게임
        {% endif %}
        </div>
    </div>
<div class="row">
    <div class="col">
        <div class="alert alert-info" role="alert">

        </div>
        <div class="game_list">
            {% for rg in games %}

                <a href="{% if rg.game_stock != 0 %}{{rg.get_gabsolute_url}}{% else %}{{rg.get_greserve_url}}{% endif %}"><div class="game">
                    <div class="game_img_div">
                        <img class="game_img" src="{{rg.game_image.url}}" alt="Game image">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{rg.game_name}}</h5>
                        <span class="device_value">{{rg.device_value}}</span>
                        <p class="card-text"><span class="price">{{rg.game_rfee|intcomma}}원</span></p>
                        {% if rg.game_stock > 0 %}
                            <p style="margin-top: 10px;">{{ rg.game_stock }}개</p>
                            <p class="game_able">대여하기</p>
                        {% else %}
                            <p class="game_able">예약하기</p>
                        {% endif %}
                        <a class="like" href="{% url 'rental:game_like' rg.game_id %}">
                            {% if i in rg.game_like.all %}
                            <img src="{% static 'image/like.png' %}">
                            {% else %}
                            <img src="{% static 'image/dislike.png' %}">
                            {% endif %}
                        </a>
                    </div>
                </div></a>
            {% endfor %}
        </div>
        <!-- 페이징처리 시작 -->
    <ul class="page">
        <!-- 이전페이지 -->
        {% if games.has_previous %}
        <li>
            <a href="?page={{ games.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li>
            <a tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->

        {% for page_number in games.paginator.page_range %}
            {% if page_number == games.number %}
            <li class="c_page">
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li>
                <a href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if games.has_next %}
        <li>
            <a href="?page={{ games.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li>
            <a tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    </div>
</div>

{% endblock %}

rental/templates/rental/rental_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Device Rental Done{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<style>
    .container{
        height: 700px;
        padding-top: 80px;
        background-image: url({% static 'image/header_back_3.png' %});
        background-size: 100px;
        font-family: 'Gothic A1', sans-serif;
    }
    .content{
        padding: 30px;
        width: 700px;
        height: 500px;
        background: white;
        margin: 0 auto;
        border: 10px solid transparent;
        border-image-source: url({% static 'image/header_border.png' %});
        border-image-slice: 9;
        border-image-repeat: round;
    }
    .content p{
        font-size: 20px;
    }
    .content h2, .content p, .content div{
        text-align: center;
    }
    .content div a{
        display: inline-block;
        padding: 5px;
        background-color: blue;
        color: white;
        border-radius: 5px;
    }
    .content img{
        animation-duration: 3s;
        animation-name: slidein;
        animation-fill-mode: forwards;
    }
    .content .d{
        text-align: left;
    }
    @keyframes slidein {
      from {
        margin-left: 0;
      }

      to {
        margin-left: 440px;
      }
    }

    /*버튼 css*/
    .btn {
        position: relative;
        border: 0;
        padding: 10px 20px;
        margin: 9px;
        display: inline-block;
        text-align: center;
        color: white;
        font-weight: 600;
        border-radius: 10px;
    }
    .btn:active {
        top: 4px;
    }
</style>
{% endblock %}
{% block content %}
<div class="content">
    <div class="d"><img src="{% static 'image/delivery-truck.png' %}" width="200px"></div>
    <h2>대여완료</h2>
    <p style="font-weight: 600;">주문이 <span style="color:orangered;">정상적으로</span> 완료되었습니다!</p>
    <p style="font-size: 17px;">&#x1F4E6;예상수령일 1~2일 이내</p>
    <div>
        <a href="{% url 'mypage:mypage' %}" class="btn yellow rounded" style="margin-left: 10px;">마이페이지</a>
        <a href="{% url 'home:home' %}" class="btn blue rounded" >메인페이지</a>
<!--        <a href="#" class="btn yellow rounded">Button</a>-->
<!--        <a href="#" class="btn green rounded">Button</a>-->
<!--		<a href="#" class="btn blue rounded">Button</a>-->
<!--		<a href="#" class="btn red rounded">Button</a>-->
<!--		<a href="#" class="btn purple rounded">Button</a>-->
<!--		<a href="#" class="btn cyan rounded">Button</a>-->

    </div>
</div>
{% endblock %}