config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('rental/', include('rental.urls')),
    path('type_test/', include('type_test.urls')),
    path('mypage/', include('mypage.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls'))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('how_to', how_to, name='how_to'),
    path('how_to_clean', how_to_clean, name='how_to_clean'),
    path('how_to_pick', how_to_pick, name='how_to_pick'),
]

mypage/urls.py
from django.urls import path
from .views import *

app_name = 'mypage'

urlpatterns = [
    path('mypage_user', mypage_user, name='mypage'),
    path('mypage_useredit', mypage_useredit, name='mypage_useredit'),
    path('mypage_game', mypage_game, name='mypage_game'),
    path('mypage_device', mypage_device, name='mypage_device'),
    path('mypage_like', mypage_like, name='mypage_like'),
    path('mypage_like/game/<int:g_id>', mypage_Gdislike, name='mypage_Gdislike'),
    path('mypage_like/device/<int:d_id>', mypage_Ddislike, name='mypage_Ddislike'),
    path('dreserve_delete/<int:drs_id>', dreserve_delete, name='dreserve_delete'),
    path('device_return/<int:dr_id>', device_return, name='device_return'),
    path('greserve_delete/<int:grs_id>', greserve_delete, name='greserve_delete'),
    path('game_return/<int:gr_id>', game_return, name='game_return'),
    path('mypage_board', mypage_board, name='mypage_board'),
]

mypage/models.py
from django.db import models

# Create your models here.

mypage/views.py
from django.core.paginator import Paginator
from django.forms import model_to_dict
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from board.models import Post
from rental.models import *


@csrf_exempt
def mypage_user(request):
    authuser = request.session.get('authUser')
    user = User.objects.get(member_id=authuser['member_id'])
    if request.method == "POST":
        user.overdue = 0
        user.save()
        return render(request, 'mypage/mypage_user.html', {'user':user})
    return render(request, 'mypage/mypage_user.html', {'user':user})


def mypage_useredit(request):
    authuser = request.session.get('authUser')
    user = User.objects.get(member_id=authuser['member_id'])
    response_data = {}
    if request.method == "POST":
        edit_id = request.POST.get('edit_id', None)
        edit_phone = request.POST.get('edit_phone', None)
        response_data['user'] = user
        if not edit_id:
            response_data['error'] = "아이디를 입력하시오."
        elif not edit_phone:
            response_data['error'] = "전화번호를 입력하시오."
        else:
            if User.objects.filter(phone=edit_phone).exclude(member_id=user.member_id):
                response_data['error'] = "이미 존재하는 전화번호입니다."
            if User.objects.filter(member_id=edit_id).exclude(phone=user.phone):
                response_data['error'] = "이미 존재하는 아이디입니다."
            else:
                user.phone = edit_phone
                user.member_id = edit_id

                if request.POST.get('another_address') :
                    user.address = request.POST.get('another_address')
                    user.address += " " + request.POST.get('another_address_detail')

                user.save()
                results = User.objects.filter(member_id=edit_id).filter(phone=edit_phone)
                authUser = results[0]
                request.session['authUser'] = model_to_dict(authUser)
                return render(request, 'mypage/mypage_user.html', {'user':user})
            return render(request, 'mypage/mypage_useredit.html', response_data)
    return render(request, 'mypage/mypage_useredit.html', {'user':user})


def mypage_game(request):
    authuser = request.session.get('authUser')
    user = User.objects.get(member_id=authuser['member_id'])
    user_grental = GameRental.objects.filter(member_id=user).order_by('-game_rental_id')
    user_greserve = GameReserve.objects.filter(member_id=user).order_by('-game_reserve_id')
    return render(request, 'mypage/mypage_game.html', {'user_grental': user_grental, 'user_greserve': user_greserve})


def mypage_device(request):
    authuser = request.session.get('authUser')
    user = User.objects.get(member_id=authuser['member_id'])
    user_drental = DeviceRental.objects.filter(member_id=user).order_by('-device_rental_id')
    user_dreserve = DeviceReserve.objects.filter(member_id=user).order_by('-device_reserve_id')

    return render(request, 'mypage/mypage_device.html', {'user_drental': user_drental, 'user_dreserve': user_dreserve,})


def mypage_like(request):
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    like_devices = RentalDevice.objects.filter(device_like=i)
    like_games = RentalGame.objects.filter(game_like=i)
    return render(request, 'mypage/mypage_like.html', {'like_devices': like_devices, 'like_games': like_games, 'i': i})


def mypage_Gdislike(request, g_id):
    g = RentalGame.objects.get(game_id=g_id)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    g.game_like.remove(i)
    return redirect('mypage:mypage_like')


def mypage_Ddislike(request, d_id):
    d = RentalDevice.objects.get(device_id= d_id)
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    d.device_like.remove(i)
    return redirect('mypage:mypage_like')


def dreserve_delete(request, drs_id):
    drs = DeviceReserve.objects.get(device_reserve_id=drs_id)
    if DeviceReserve.objects.filter(device_id=drs.device_id).count() == 1:
            if DeviceRental.objects.filter(device_id=drs.device_id, overdue=None).count() == 0:
                rd = RentalDevice.objects.get(device_name=drs.device_id)
                rd.device_check = 0
                rd.save()
    else:
        drss = DeviceReserve.objects.filter(device_reserve_id__gt=drs_id, device_id=drs.device_id)
        for i in drss:
            i.device_due_date = i.device_due_date - timedelta(days=15)
            i.save()
    drs.delete()
    return redirect('mypage:mypage_device')


def device_return(request, dr_id):
    dr = DeviceRental.objects.get(device_rental_id=dr_id)
    drs = DeviceReserve.objects.filter(device_id=dr.device_id)
    if datetime.now().date() < dr.dreturn_date:
        dr.overdue = 0
        date = dr.dreturn_date - datetime.now().date()
    else:
        date = datetime.now().date() - dr.dreturn_date
        dr.overdue = date.days + 1
        authuser = request.session.get('authUser')
        user = User.objects.get(member_id=authuser['member_id'])
        user.overdue = user.overdue + dr.overdue
        user.save()

    if drs.count() == 0:
        rd = RentalDevice.objects.get(device_name=dr.device_id)
        rd.device_check = 0
        rd.save()

    dr.dreturn_date = datetime.now().date() + timedelta(days=1)
    dr.save()

    for i in drs:
        i.device_due_date = i.device_due_date - timedelta(days=date.days-1)
        i.save()

    return redirect('mypage:mypage_device')


def greserve_delete(request, grs_id):
    grs = GameReserve.objects.get(game_reserve_id=grs_id)

    if GameReserve.objects.filter(game_id=grs.game_id).count() == 1:
        if GameRental.objects.filter(game_id=grs.game_id, overdue=None).count() == 0:
            rg = RentalGame.objects.get(game_name=grs.game_id)
            rg.game_stock = rg.game_stock + 1
            rg.save()
    else:
        grss = GameReserve.objects.filter(game_reserve_id__gt=grs_id, game_id=grs.game_id)
        for i in grss:
            i.game_due_date = GameReserve.objects.get(game_reserve_id=i.game_reserve_id-1).game_due_date
            i.save()

    grs.delete()
    return redirect('mypage:mypage_game')


def game_return(request, gr_id):
    gr = GameRental.objects.get(game_rental_id=gr_id)

    grs = GameReserve.objects.filter(game_id=gr.game_id)

    gr.greturn_date = datetime.now().date() + timedelta(days=1)
    if datetime.now().date() < gr.greturn_date:
        gr.overdue = 0

        if grs.count() == 0:
            rg = RentalGame.objects.get(game_name=gr.game_id)
            rg.game_stock = rg.game_stock + 1
            rg.save()
        else:
            grs_f = grs.first()
            grs_f.game_due_date = gr.greturn_date + timedelta(days=2)
            grs_f.save()
    else:
        date = datetime.now().date() - gr.greturn_date
        gr.overdue = date.days
    gr.save()

    return redirect('mypage:mypage_game')


def mypage_board(request):
    authuser = request.session.get('authUser')
    i = User.objects.get(member_id=authuser['member_id'])
    b = Post.objects.filter(member_id=i)
    page = request.GET.get('page', '1')
    paginator = Paginator(b, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    return render(request, 'mypage/mypage_board.html', {'b': page_obj,})

mypage/templates/mypage/mypage.html
{% extends 'base.html' %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}
{% block style %}
{% endblock %}
{% block content %}

<div class="mypage_menu">
    <ul><legend>마이페이지</legend>
        <li><a href="{% url 'mypage:mypage' %}">회원정보</a></li>
        <li><a href="{% url 'mypage:mypage_game' %}">게임 대여/예약</a></li>
        <li><a href="{% url 'mypage:mypage_device' %}">기기 대여/예약</a></li>
        <li><a href="{% url 'mypage:mypage_like' %}">관심목록</a></li>
        <li><a href="{% url 'mypage:mypage_board' %}">게시물관리</a></li>
    </ul>
</div>
{% block contents %}
{% endblock %}
{% endblock %}

mypage/templates/mypage/mypage_device.html
{% extends 'mypage/mypage.html' %}
{% load static %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<style>
    ul{
        padding: 0;
        margin: 0;
    }
    li{
        list-style: none;
    }
    legend{
        font-weight: bold;
        margin: 0;
    }
    .container{
        display: flex;
    }
    .mypage_menu{
        width: 200px;
        text-align: center;
        margin-right: 20px;
    }
    .mypage_menu ul{
        border: 1px solid black;
        border-radius: 5px;
        padding: 10px;
    }
    .mypage_menu li{
        border-bottom: 1px solid lightgray;
        height: 40px;
        line-height: 40px;
    }
    .mypage_main table{
        text-align: center;
        border-top: 1px solid black;
        border-collapse: collapse;
    }
    .mypage_main th{
        background-color: gray;
        color: white;
        width: 200px;
    }
    .mypage_main th, .mypage_main td{
        border-bottom: 1px solid black;
        border-left: 1px solid black;
        padding: 5px;
    }
    .mypage_main th:first-child, .mypage_main td:first-child {
        border-left: none;
    }
    .mypage_main legend{
        margin: 5px;
        margin-left: 0;
    }
    /*버튼 css*/
    .btn {
        position: relative;
        border: 0;
        padding: 5px 10px;
        height: 28px;
        margin: 10px;
        display: inline-block;
        text-align: center;
        color: white;
        font-weight: 600;
        font-size: 14px;
        border-radius: 5px;
    }
    .btn:active {
        top: 4px;
    }
</style>
{% endblock %}
{% block contents %}
{% if request.session.authUser is None %}
비로그인 상태
{% else %}
<div class="mypage_main">
    반납 신청은 반드시 반납 예정일 하루 전날까지 하시오.
    <hr>

    <legend>기기 대여 목록</legend>
    {% if user_drental|length == 0 %}
    대여 목록이 없습니다.
    {% else %}
    <table>
        <thead>
        <th style="width: 150px;">기기 이름</th>
        <th>대여 시작 일자</th>
        <th>반납 일자</th>
        <th>반납 신청</th>
        </thead>
        <tbody>
        {% for dr in user_drental %}
        <tr>
            <td>{{ dr.device_id }}</td>
            <td>{{ dr.drental_date }}</td>
            <td>{{ dr.dreturn_date }}{% if dr.overdue == None %}(예정){% else %}{% endif %}</td>
            <td>
                {% if dr.overdue == None %}
                <a href="{% url 'mypage:device_return' dr.device_rental_id %}" class="btn blue rounded">반납 신청</a>
                {% else %}
                반납완료
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    <br>
    <legend>기기 예약 목록</legend>
        {% if user_dreserve|length == 0 %}
        예약 목록이 없습니다.
        {% else %}
    <table>
        <thead>
        <th style="width: 150px;">기기 이름</th>
        <th>예약 일자</th>
        <th>예상 대여 시작 일자</th>
        <th>예약 취소</th>
        </thead>
        <tbody>
        {% for drs in user_dreserve %}
        <tr>
            <td>{{ drs.device_id }}</td>
            <td>{{ drs.device_reserve_date }}</td>
            <td>{{ drs.device_due_date }}</td>
            <td>
                <a href="{% url 'mypage:dreserve_delete' drs.device_reserve_id %}" class="btn red rounded">예약 취소</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        {% endif %}
    </table>
    {% endif %}
</div>
{% endblock %}

mypage/templates/mypage/mypage_game.html
{% extends 'mypage/mypage.html' %}
{% load static %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<style>
    ul{
        padding: 0;
        margin: 0;
    }
    li{
        list-style: none;
    }
    legend{
        font-weight: bold;
        margin: 0;
    }
    .container{
        display: flex;
    }
    .mypage_menu{
        width: 200px;
        text-align: center;
        margin-right: 20px;
    }
    .mypage_menu ul{
        border: 1px solid black;
        border-radius: 5px;
        padding: 10px;
    }
    .mypage_menu li{
        border-bottom: 1px solid lightgray;
        height: 40px;
        line-height: 40px;
    }

    .mypage_main table{
        text-align: center;
        border-top: 1px solid black;
        border-collapse: collapse;
    }
    .mypage_main th{
        background-color: gray;
        color: white;
        width: 200px;
    }
    .mypage_main th, .mypage_main td{
        border-bottom: 1px solid black;
        border-left: 1px solid black;
        padding: 5px;
    }
    .mypage_main th:first-child, .mypage_main td:first-child {
        border-left: none;
    }
    .mypage_main legend{
        margin: 5px;
        margin-left: 0;
    }
    /*버튼 css*/
    .btn {
        position: relative;
        border: 0;
        padding: 5px 10px;
        height: 28px;
        margin: 10px;
        display: inline-block;
        text-align: center;
        color: white;
        font-weight: 600;
        font-size: 14px;
        border-radius: 5px;
    }
    .btn:active {
        top: 4px;
    }
</style>
{% endblock %}
{% block contents %}
{% if request.session.authUser is None %}
비로그인 상태
{% else %}
<div class="mypage_main">
    반납 신청은 반드시 반납 예정일 하루 전날까지 하시오.
    <hr>

    <legend>게임 대여 목록</legend>
    {% if user_grental|length == 0 %}
        대여 목록이 없습니다.
    {% else %}
    <table>
        <thead>
        <th style="width: 150px;">게임 이름</th>
        <th>대여 시작 일자</th>
        <th>반납 일자</th>
        <th>반납 신청</th>
        </thead>
        <tbody>
        {% for gr in user_grental %}
        <tr>
            <td>{{ gr.game_id }}</td>
            <td>{{ gr.grental_date }}</td>
            <td>{{ gr.greturn_date }}{% if gr.overdue == None %}(예정){% else %}{% endif %}</td>
            <td>
                {% if gr.overdue == None %}
                <a href="{% url 'mypage:game_return' gr.game_rental_id %}" class="btn blue rounded">반납 신청</a>{% else %}반납완료
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    <br>
    <legend>게임 예약 목록</legend>
    {% if user_greserve|length == 0 %}
        예약 목록이 없습니다.
    {% else %}
    <table>
        <thead>
        <th style="width: 150px;">게임 이름</th>
        <th>예약 일자</th>
        <th>예상 대여 시작 일자</th>
        <th>예약 취소</th>
        </thead>
        <tbody>
        {% for grs in user_greserve %}
        <tr>
            <td>{{ grs.game_id }}</td>
            <td>{{ grs.game_reserve_date }}</td>
            <td>{{ grs.game_due_date }}</td>
            <td>
                <a href="{% url 'mypage:greserve_delete' grs.game_reserve_id %}" class="btn red rounded">예약 취소</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        {% endif %}
    </table>
    {% endif %}
</div>
{% endblock %}

mypage/templates/mypage/mypage_like.html
{% extends 'mypage/mypage.html' %}
{% load static %}
{% load humanize %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
<script>

</script>
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<style>
    h5{
        font-size: 16px;
        display: inline;
    }
    p{
        margin: 0;
    }
    ul{
        padding: 0;
        margin: 0;
    }
    li{
        list-style: none;
    }
    .container{
        display: flex;
    }
    .list{
        width: 450px;
    }
    .mypage_menu{
        width: 200px;
        text-align: center;
        margin-right: 20px;
    }
    .mypage_menu ul{
        border: 1px solid black;
        border-radius: 5px;
        padding: 10px;
    }
    .mypage_menu li{
        border-bottom: 1px solid lightgray;
        height: 40px;
        line-height: 40px;
    }
    legend{
        font-weight: bold;
        margin: 0;
    }

    .device_list{
        display:flex;
        flex-wrap: wrap;
        border: 2px solid white;
    }
    .device{
        position: relative;
        padding: 10px;
        width: 200px;
        height: 320px;
        margin-bottom: 20px;
        margin-right: 20px;
        border: 1px solid lightgray;
        border-radius: 5px;
    }
    .device:nth-child(odd){
        margin-right: 0;
    }
    .pub{
        font-size: 15px;
        color: gray;
    }
    .device_img_div{
        position: relative;
       display: flex;
       align-items: center;
       width: 180px;
       height: 230px;
    }
    .device_img_div p{
        position: absolute;
        bottom: 0;
        right: 0;
        font-size: 13px;
        margin: 0;
        background-color: white;
    }
    .device_img{
        width: 180px;
    }

    .price{
        position: absolute;
        bottom: 0;
        left: 5px;
        line-height: 35px;
    }
    .device_able{
        position: absolute;
        line-height: 35px;
        bottom: 2px;
        right: 50px;
        margin: 0;
    }

    .game_list{
        display:flex;
        flex-wrap: wrap;
    }
    .game{
        position: relative;
        padding: 5px;
        width: 200px;
        height: 320px;
        border: 2px solid black;
        margin-bottom: 20px;
        margin-right: 20px;
        border: 1px solid lightgray;
        border-radius: 5px;
    }
    .game:nth-child(odd){
        margin-right: 0;
    }
    .device_value{
        font-size: 15px;
        color: gray;
    }
    .game_img_div{
       display: flex;
       align-items: center;
       width: 180px;
       height: 200px;
    }
    .game_img{
        width: 180px;
    }

    .game_able{
        position: absolute;
        line-height: 35px;
        bottom: 2px;
        right: 50px;
        margin: 0;
    }

    /*버튼 css*/
    .btn {
        position: absolute;
        bottom: 10px;
        right: 10px;
        border: 0;
        padding: 2px 5px;
        text-align: center;
        color: white;
        font-weight: 600;
        font-size: 12px;
        border-radius: 3px;
        cursor: pointer;
    }
    .btn:active{
        bottom: 5px;
    }

</style>
{% endblock %}
{% block contents %}

<div class="list"><h2>기기</h2>
    <div class="device_list">
    {% for rd in like_devices %}
        <a href="{% if rd.device_check == 0 %}
                   {{rd.get_dabsolute_url}}
                  {% else %}
                    {{rd.get_dreserve_url}}
                    {% endif %}">
            <div class="device">
            <div class="device_img_div">
                <img class="device_img" src="{{rd.device_image.url}}" alt="device image">
                <p>상태 : {{ rd.device_state }}</p>
            </div>
            <div>
                <h5 class="card-title">{{rd.device_name|upper}}</h5>
                <span class="pub">{{rd.device_pub|date:"Y"}}</span>
                <p class="price">{{rd.device_rfee|intcomma}}원</p>
                {% if rd.device_check == 0 %}
                    <p class="device_able">대여 가능</p>
                {% else %}
                    <p class="device_able">예약하기</p>
                {% endif %}
                <a class="btn red rounded" href="{% url 'mypage:mypage_Ddislike' rd.device_id %}">
                    삭제
                </a>
            </div>
        </div></a>
            {% endfor %}
    </div>
</div>

<div class="list"><h2>게임</h2>
    <div class="game_list">
            {% for rg in like_games %}

                <a href="{% if rg.game_stock != 0 %}{{rg.get_gabsolute_url}}{% else %}{{rg.get_greserve_url}}{% endif %}"><div class="game">
                    <div class="game_img_div">
                        <img class="game_img" src="{{rg.game_image.url}}" alt="Game image">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{rg.game_name}}</h5>
                        <span class="device_value">{{rg.device_value}}</span>
                        <p class="card-text"><span class="price">{{rg.game_rfee|intcomma}}원</span></p>
                        {% if rg.game_stock > 0 %}
                            <p style="margin-top: 10px;">{{ rg.game_stock }}개</p>
                            <p class="game_able">대여 가능</p>
                        {% else %}
                            <p class="game_able">예약하기</p>
                        {% endif %}
                        <a class="btn red rounded" href="{% url 'mypage:mypage_Gdislike' rg.game_id %}">
                            삭제
                        </a>
                    </div>
                </div></a>
            {% endfor %}
        </div>
</div>
{% endblock %}

mypage/templates/mypage/mypage_user.html
{% extends 'mypage/mypage.html' %}
{% load static %}
{% block title %}NoPainNoGame{% endblock %}
{% block script %}
<meta charset="utf-8" />
<script src="http://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="http://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
<script>
function requestPay() {
    var IMP = window.IMP;
    var code = "imp94855493";  // FIXME: 가맹점 식별코드
    IMP.init(code);
      IMP.request_pay({ // param
          pg: "html5_inicis",
          pay_method: "card",
          merchant_uid: 'merchant_' + new Date().getTime(),
          name: "연체료 결제",
          amount:  {{user.overdue}}*1000,
          buyer_name: "{{ user.member_name }}",
      }, function (rsp) { // callback
          if (rsp.success) {
              $('.pay').submit();
              jQuery.ajax({
                url: "{/mypage/mypage_user}",
                method: "POST",
                headers: { "Content-Type": "application/json" },
                data: {
                    imp_uid: rsp.imp_uid,
                    merchant_uid: rsp.merchant_uid
                }
            }).done(function (data) {
              // 가맹점 서버 결제 API 성공시 로직
            })
          } else {
            alert("결제에 실패하였습니다. 에러 내용: " +  rsp.error_msg);
          }
      });
    }
</script>
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<style>
    ul{
        padding: 0;
        margin: 0;
    }
    li{
        list-style: none;
    }
    .container{
        display: flex;
    }
    .mypage_menu{
        width: 200px;
        text-align: center;
        margin-right: 20px;
    }
    .mypage_menu ul{
        border: 1px solid black;
        border-radius: 5px;
        padding: 10px;
    }
    .mypage_menu li{
        border-bottom: 1px solid lightgray;
        height: 40px;
        line-height: 40px;
    }
    legend{
        font-weight: bold;
        margin: 0;
    }
    .mypage_content{
        width: 900px;
        margin: 0 auto;
    }
    .mypage_content table{
        width: 100%;
        text-align: center;
        border-bottom: 1px solid black;
        border-collapse: collapse;
    }
    .mypage_content tr{
        height: 40px;
        border-top: 1px solid gray;
    }
    .mypage_content td{
        padding: 12px;
    }
    .mypage_content td:nth-child(1){
        text-align: left;
    }
    .mypage_content td:nth-child(2){
        width: 550px;
        text-align: left;
    }

    /*버튼 css*/
    .btn {
        position: relative;
        border: 0;
        padding: 6px 12px;
        margin: 10px;
        display: inline-block;
        text-align: center;
        color: white;
        font-weight: 600;
        font-size: 14px;
        border-radius: 5px;
    }
    .btn:active {
        top: 4px;
    }

</style>
{% endblock %}
{% block contents %}
<div class="mypage_content">
    <h3>나의 정보</h3>
    <table>
        <tr>
            <td>이름</td>
            <td>{{user.member_name}}</td>
        </tr>
        <tr>
            <td>아이디</td>
            <td>{{user.member_id}}</td>
        </tr>
        <tr>
            <td>전화번호</td>
            <td>{{user.phone}}</td>
        </tr>
        <tr>
            <td>주소</td>
            <td>{{user.address}}</td>
        </tr>
        <tr>
            <td>연체 상황&#42;</td>
            <td style="display: relative;">{{user.overdue}}일<form style="position: absolute; width: 100px; margin-top: -37.5px; right: 45px;" class="pay" method="POST"><input type="button" class="btn purple rounded" onclick="requestPay()" value="연체료 결제"></form></td>
        </tr>
        <tr>
            <td>게임 유형</td>
            <td>{% if user.type_id == 1 %}
                날쌘돌이 구름이
                {% elif user.type_id == 2 %}
                심플프리덤 감자
                {% elif user.type_id == 3 %}
                두뇌풀가동 전사
                {% elif user.type_id == 4 %}
                재기발랄 모험가{% endif %}
            </td>
        </tr>
    </table>
    <p style="margin: 5px 0 0 0;">※현재 연체 중인 상황은 반영되지 않음</p>
    <p style="text-align: right;"><a href="{% url 'mypage:mypage_useredit' %}" class="btn cyan rounded">수정하기</a></p>
</div>
{% endblock %}