account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('find_id/', find_id, name='find_id'),
    path('find_pw/', find_pw, name='find_pw'),
]

board/urls.py
from django.urls import path
from .views import *

app_name = 'board'

urlpatterns = [
    path('', board, name='board'),
    path('write', board_write, name='board_write'),
    path('postwrite', board_write_post, name='board_write_post'),
    path('delete/<p_id>', board_delete, name='board_delete'),
    path('edit/<p_id>', board_edit, name='board_edit'),
    path('<p_type>', board, name='board'),
    path('detail/<id>', board_detail, name='board_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('rental/', include('rental.urls')),
    path('type_test/', include('type_test.urls')),
    path('mypage/', include('mypage.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls'))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('how_to', how_to, name='how_to'),
    path('how_to_clean', how_to_clean, name='how_to_clean'),
    path('how_to_pick', how_to_pick, name='how_to_pick'),
]

mypage/urls.py
from django.urls import path
from .views import *

app_name = 'mypage'

urlpatterns = [
    path('mypage_user', mypage_user, name='mypage'),
    path('mypage_useredit', mypage_useredit, name='mypage_useredit'),
    path('mypage_game', mypage_game, name='mypage_game'),
    path('mypage_device', mypage_device, name='mypage_device'),
    path('mypage_like', mypage_like, name='mypage_like'),
    path('mypage_like/game/<int:g_id>', mypage_Gdislike, name='mypage_Gdislike'),
    path('mypage_like/device/<int:d_id>', mypage_Ddislike, name='mypage_Ddislike'),
    path('dreserve_delete/<int:drs_id>', dreserve_delete, name='dreserve_delete'),
    path('device_return/<int:dr_id>', device_return, name='device_return'),
    path('greserve_delete/<int:grs_id>', greserve_delete, name='greserve_delete'),
    path('game_return/<int:gr_id>', game_return, name='game_return'),
    path('mypage_board', mypage_board, name='mypage_board'),
]

rental/urls.py
from django.urls import path
from rental.views import *

app_name = 'rental'

urlpatterns = [
    path('device/list/', device_list, name='device_list_all'),
    path('device/list/<d_values>', device_list, name='device_list'),
    path('device/like/<int:d_id>/', device_like, name="device_like"),
    path('device/<int:d_id>/<d_name>/detail', device_detail, name='device_detail'),
    path('device/<int:d_id>/rent', device_rental, name='device_rental'),
    path('device/<int:d_id>/reserve', device_reserve, name='device_reserve'),
    path('game/list/', game_list, name='game_list_all'),
    path('game/list/device/<g_device>', game_list, name='game_list'),
    path('game/list/genre/<g_genre>', game_list, name='game_list_genre'),
    path('game/like/<int:g_id>/', game_like, name="game_like"),
    path('game/<g_id>/', game_detail, name='game_detail'),
    path('game/<g_id>/rent', game_rental, name='game_rental'),
    path('game/<int:g_id>/reserve', game_reserve, name='game_reserve'),
    path('rental_done', rental_done, name='rental_done'),
    path('reserve_done', reserve_done, name='reserve_done'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>No Pain No Game</title>
        <meta charset="UTF-8">
        <style>
            *{
                box-sizing: border-box;
            }
            html, body {
            width:100vw; /* or % */
            height:100vh; /* or % */
            overflow-x: hidden;
            }
            ul{
                padding: 0;
            }
            li{
                list-style: none;
            }
            @font-face {
                font-family: 'NeoDunggeunmo';
                src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.3/NeoDunggeunmo.woff') format('woff');
                font-weight: normal;
                font-style: normal;
            }
            @font-face {
                font-family: 'Dunggeunmo';
                src: url({% static 'css/DungGeunMo.ttf' %});
                format('truetype');
            }
            body{
                margin: 0;
                background-image: url({% static 'image/배경구름1.png' %});
                background-size: 240px auto;
                overflow-x: hidden;
            }
            body::-webkit-scrollbar {
                background: transparent;
                width: 8px;

            }
            body::-webkit-scrollbar-thumb{
                background-color: white;
                border-radius: 5px;
            }
            .header{
                padding-top: 18px;
                border-top: 19px solid transparent;
                border-bottom: 19px solid transparent;
                border-image-source: url({% static 'image/header_border.png' %});
                border-image-slice: 13;
                border-image-repeat: round;
                background-image: url({% static 'image/header_back_1.png' %});
                background-size: 70px auto;
                width: 100%;
                height: 180px;
                position: relative;
                align-items: center;
                font-family: 'Dunggeunmo', sans-serif;

                background-color: rgba(255, 255, 255, 0);
            }
            a{
                text-decoration: none;
                color: black;
            }
            .header nav a, .log a{
                color: #F6F1EBFF;
                text-shadow: -2px 0 #5F381EFF, 0 2px #5F381EFF, 2px 0 #5F381EFF, 0 -2px #5F381EFF;
            }
            .header h1{
                font-family: 'NeoDunggeunmo', sans-serif;
                margin: 0;
                text-align: center;
                font-size: 70px;
                text-shadow: -3px 0 #734425FF, 0 3px #734425FF, 3px 0 #734425FF, 0 -3px #734425FF;
            }
            .header h1 a{
                color: #341E12FF;
            }
            nav{
                width: 100%;
                margin: 0 auto;
                margin-top: 14px;
                justify-content: center;
                position: relative;
            }
            .text p{
                margin: 16px 0;
            }
            nav ul{
                list-style: none;
                display: flex;
                justify-content: center;
                padding: 0;
                margin: 0;
                font-weight: 0;
                padding-left: 50px;
                padding-right: 50px;
            }
            nav li{
                width: 170px;
                text-align: center;
                font-size: 25px;
                margin: 0 10px 0 10px;
            }
            .container{
                width: 1180px;
                min-height: 90%;
                margin: 0 auto;
                background-color: white;
                padding: 20px;
                padding-bottom: 50px;
                position: relative;
            }

            .goTop{
                position: fixed;
                bottom: 30px;
                right: 30px;
                font-family: 'NeoDunggeunmo';
                text-align: center;
            }

            .goTop div {
                padding-bottom: 5px;
                padding-left: 5px;
                font-size: 18px;
                font-weight: bold;
            }
            .goTop img{
                width: 40px;
            }
            .log{
                position: absolute;
                top: -19px;
                left: 0;
                width: 400px;
                height: 180px;
                display: flex;
            }
            .log .text{
                text-align: left;
                width: 220px;
                padding: 10px;
                padding-top: 23px;

            }
            .log img{
                width: 180px;
            }
            .postbox{
                position: absolute;
                top: 0px;
                right: 20px;
                width: 130px;
                height: 170px;
            }
            .postbox img{
                position: absolute;
                top: 0;
                left: 0;
                width: 130px;
            }
            .notice_no{
                position: absolute;
                background-color:red;
                color: white;
                width: 30px;
                height: 30px;
                line-height: 30px;
                text-align: center;
                border-radius: 50%;
                top: 5px;
                left: -5px;
            }
            .post_default:hover{
                display: none;
            }
            .post_hover{
                opacity: 0;
            }
            .post_hover:hover{
                opacity: 1;
            }
            .postbox a{
                display: block;
                width: 130px;
                height: 170px;
            }
            #notice{
                display: none;
                position: absolute;
                right: 19px;
                top: -19px;
                width: 300px;
                min-height: 150px;
            }
            #notice:target{
                display: block;
            }
            .ext{
                position: absolute;
                top: 29px;
                right: 10px;
                font-weight: bolder;
                color: #6F3A22FF;
                font-size: 25px;
            }
            .notice_contents{
                background-color: #E4BD74FF;
                margin-top: 25px;
                height: 130px;
                width: 100%;
                padding: 20px;
            }
            .notice_contents ul{
                padding-left: 20px;
            }
            footer{
                position: relative;
                width: 100%;
                background-image: url({% static 'image/배경바닥.png' %});
                text-align: center;
                height: 180px;
                background-size: 300px 100%;
                margin-top: -30px;
                color: white;
                font-weight: bolder;
                padding-top: 90px;
            }
            footer table{
                margin: 0 auto;
            }
            footer table td{
                width: 240px;
                text-align: left;
                padding-left: 5px;
            }
            footer table td:nth-child(1){
                text-align: right;
                border-right: 4px dotted white;
                padding-right: 5px;
                padding-left: 0;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script>
            window.onfocus=function(){}
            window.onload=function(){
                window.focus();
                window.resizeTo(1335, 750)
            }
        </script>
        {% block script %}
        {% endblock %}
        {% block style %}
        {% endblock %}

    </head>
    <body>
        <div class="header" id="top">

            <h1><a href="{% url 'home:home' %}">No Pain No Game</a></h1>
            <nav>
                <ul>
                    <a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'type_test:type_test' %}{% endif %}"><li>
                        <div>유형테스트</div>
                    </li></a>
                    <a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'rental:device_list_all' %}{% endif %}"><li>
                        <div>기기대여</div>
                    </li></a>
                    <a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'rental:game_list_all' %}{% endif %}"><li>
                        <div>게임대여</div>
                    </li></a>
                    <a href="{% if request.session.authUser is None %}{% url 'account:login' %}{% else %}{% url 'board:board' %}{% endif %}"><li>
                        <div>게시판</div>
                    </li></a>
                </ul>
            </nav>
            <div class="log">
                <div class="image">
                    {% if request.session.authUser.type_id == 1 %}
                        <img src="{% static 'image/speed.png' %}">
                    {% elif request.session.authUser.type_id == 2 %}
                        <img src="{% static 'image/simple.png' %}">
                    {% elif request.session.authUser.type_id == 3 %}
                        <img src="{% static 'image/competition.png' %}">
                    {% elif request.session.authUser.type_id == 4 %}
                        <img src="{% static 'image/explorer.png' %}">
                    {% else %}
                        <img src="{% static 'image/no_type.png' %}">
                    {% endif %}
                </div>
                <div class="text">
                    {% if request.session.authUser is None %}
                        <span style="margin-right:5px;"><a href="{% url 'account:login' %}">login</a></span>
                        <span><a href="{% url 'account:register' %}">signin</a></span>
                    {% else %}

                        <span class="member_id" style="color: white;">{{request.session.authUser.member_id}}</span>

                        <span><a href="{% url 'account:logout' %}">logout</a></span>
                        <p><a href="{% url 'mypage:mypage' %}">마이페이지</a></p>

                    {% endif %}

                </div>

            </div>
            <div class="postbox">
                {% if request.session.authUser is None %}
                    <img src="{% static 'image/postbox1.png' %}">
                {% else %}
                    {% if notice_no >= 1 %}
                        <a href="#notice">
                            <img class="post_default" src="{% static 'image/postbox_post.png' %}">
                            <img class="post_hover" src="{% static 'image/postbox_post_shadow.png' %}">
                            <div class="notice_no">{{ notice_no }}</div>
                        </a>
                    {% else %}
                            <img src="{% static 'image/postbox1.png' %}">
                    {% endif %}
                {% endif %}
            </div>
            <div id="notice">
                <div class="notice_contents">
                    <ul>
                    {% for d_rental in device_rental %}
                        {% if dr_day == 0 %}
                            <li>{{d_rental.device_id}} 반납 기간 임박 ({{d_rental.dreturn_date}})</li>
                        {% else %}
                            <li>{{d_rental.device_id}} {{dr_day}}일 연체</li>
                        {% endif %}
                    {% endfor %}
                    {% for g_rental in game_rental %}
                        {% if gr_day == 0 %}
                            <li>{{g_rental.game_id}} 반납 기간 임박 ({{g_rental.greturn_date}})</li>
                        {% else %}
                            <li>{{g_rental.game_id}} {{gr_day}}일 연체</li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                    <a class="ext" href="/">X</a>
                </div>
            </div>
        </div>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <footer>
            <div>
                <table>
                    <tr>
                        <td>법인명 (주)NoPainNoGame</td>
                        <td>대표이사 주서영</td>
                    </tr>
                    <tr>
                        <td>사업자등록번호 000-00-0000</td>
                        <td>주소 서울특별시</td>
                    </tr>
                    <tr>
                        <td>제휴문의</td>
                        <td>9139a90@naver.com</td>
                    </tr>

                </table>
            </div>
        </footer>
        <a href="#top">
            <div class="goTop">
                <div>up!</div>
                <img src="{% static 'image/로켓.png' %}">
            </div>
        </a>
    </body>
</html>